apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: ipiece-slack
  namespace: monitoring
  labels:
    alertmanagerConfig: ipiece
spec:
  route:
    groupBy: ['alertname', 'namespace']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h

    routes:
      # 앱 알람
      - matchers:
          - 'alert_team="app"'
        receiver: slack-app

      # EKS 인프라 알람
      - matchers:
          - 'alert_team="infra"'
          - 'infra="eks"'
        receiver: slack-eks-infra

      # 온프렘 인프라 알람
      - matchers:
          - 'alert_team="infra"'
          - 'infra="onprem"'
        receiver: slack-onprem-infra

    receiver: slack-main

  receivers:
    - name: slack-app
      slackConfigs:
        - apiURL:
            name: alertmanager-slack-app-webhook
            key: slack_api_url
          sendResolved: true

    - name: slack-eks-infra
      slackConfigs:
        - apiURL:
            name: alertmanager-slack-eks-webhook
            key: slack_api_url
          sendResolved: true

    - name: slack-onprem-infra
      slackConfigs:
        - apiURL:
            name: alertmanager-slack-onprem-webhook
            key: slack_api_url
          sendResolved: true

    - name: slack-main
      slackConfigs:
        - apiURL:
            name: alertmanager-slack-webhook
            key: slack_api_url
          sendResolved: true
