apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: ipiece-slack
  namespace: monitoring
  labels:
    alertmanagerConfig: ipiece
spec:
  route:
    receiver: slack-main
    groupBy: ['alertname', 'namespace']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h

  receivers:
    - name: slack-main
      slackConfigs:
        - apiURL:
            name: alertmanager-slack-webhook   # Secret 이름
            key: slack_api_url                 # 그 안의 key
          channel: '#ipiece-alarm'
          sendResolved: true
