apiVersion: v2
name: ipiece-monitoring
description: Monitoring Stack (Prometheus + Loki + Grafana + OTel)
type: application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 61.3.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki-stack
    version: 2.10.2
    repository: https://grafana.github.io/helm-charts
  
  # 👇 [추가] OTel Collector 차트
  - name: opentelemetry-collector
    version: 0.97.1
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    alias: otel