kind: Kustomization


namespace: default

images:
- name: 235625001959.dkr.ecr.ap-northeast-2.amazonaws.com/ipiece-server
  newName: 235625001959.dkr.ecr.ap-northeast-2.amazonaws.com/ipiece-server
  newTag: 0d4d2fa
- name: ipiece-server
  newName: 235625001959.dkr.ecr.ap-northeast-2.amazonaws.com/ipiece-server
  newTag: latest

replicas:
- count: 1
  name: ipiece-server

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "dev"
  target:
    kind: Deployment
    name: ipiece-server
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ../../base
