apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: default

images:
- name: ipiece-server
  newName: 235625001959.dkr.ecr.ap-northeast-2.amazonaws.com/ipiece-server
  newTag: latest

replicas:
- name: ipiece-server
  count: 1

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "dev"
  target:
    kind: Deployment
    name: ipiece-server
