
resources:
- ../../base
- ServiceAccount.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: 235625001959.dkr.ecr.ap-northeast-2.amazonaws.com/ipiece-server
  newName: 235625001959.dkr.ecr.ap-northeast-2.amazonaws.com/ipiece-server
  newTag: 2badc9d-57
kind: Kustomization
