apiVersion: v1
kind: ServiceAccount
metadata:
  name: ipiece-backend-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::235625001959:oidc-provider/oidc.eks.ap-northeast-2.amazonaws.com/id/85741B40F2E009117BEA572204C26FE3