# system/cluster-autoscaler/cluster-autoscaler-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
        - name: cluster-autoscaler
          image: registry.k8s.io/autoscaling/cluster-autoscaler:v1.30.0
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
          args:
            - --cloud-provider=aws
            - --cluster-name=ipiece-cluster1

            # 🔥 ASG 태그 기반 노드 그룹 자동 발견
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/ipiece-cluster1

            # 🔁 비슷한 노드 그룹끼리 균형 맞추기
            - --balance-similar-node-groups=true

            # 🧹 scale-down 동작 튜닝 (여기가 핵심)
            - --scale-down-enabled=true               # 줄이기 켜기
            - --scan-interval=30s                     # 30초마다 체크
            - --scale-down-unneeded-time=10m          # 10분 동안 쓸모없으면 후보
            - --scale-down-utilization-threshold=0.5  # 노드 평균 사용률 50% 미만이면 저부하

            # 기타 동작
            - --skip-nodes-with-local-storage=false
            - --skip-nodes-with-system-pods=false
            - --expander=least-waste
            - --stderrthreshold=info
            - --v=4
          env:
            - name: AWS_REGION
              value: ap-northeast-2
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt
              readOnly: true
          imagePullPolicy: Always
      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs/ca-bundle.crt
            type: FileOrCreate
