# system/cluster-autoscaler/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - cluster-autoscaler-sa-rbac.yaml
  - cluster-autoscaler-deployment.yaml

commonLabels:
  app: cluster-autoscaler
