apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ipiece-backend-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing

    alb.ingress.kubernetes.io/target-type: ip

    alb.ingress.kubernetes.io/group.name: ipiece

    alb.ingress.kubernetes.io/healthcheck-path: /api/healthz
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: ipiece-server
                port:
                  number: 80