apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ipiece-frontend
  newName: 235625001959.dkr.ecr.ap-northeast-2.amazonaws.com/ipiece-frontend
  newTag: 6ae53e5e0d7198adea1e5efa3362a8e1aef70537-19781417447-2
