apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ipiece-frontend
  newName: 235625001959.dkr.ecr.ap-northeast-2.amazonaws.com/ipiece-frontend
  newTag: bb321e4b140d041e2a1dbcfc653f03def4adedc9-19797090649-1
