aws-load-balancer-controller:
  clusterName: ipiece-cluster1
  region: ap-northeast-2
  vpcId: vpc-087decd9f8cc89873

  serviceAccount:
    create: true
    name: aws-load-balancer-controller
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::235625001959:role/aws-load-balancer-controller

  # 🔽 system 노드에서만 띄우기
  nodeSelector:
    role: "system"
  tolerations:
    - key: "system"
      operator: "Equal"
      value: "core"
      effect: "NoSchedule"
