apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ipiece-frontend
  newName: 235625001959.dkr.ecr.ap-northeast-2.amazonaws.com/ipiece-frontend
  newTag: 5cf0e2aea989a7766812b328c6b49384b7d0e393

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: ipiece-frontend
