apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ipiece-frontend
  newName: 235625001959.dkr.ecr.ap-northeast-2.amazonaws.com/ipiece-frontend
  newTag: 6bb99bb71f6de71d19ca530d17d8caa18bdaad58

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: ipiece-frontend
