apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ipiece-frontend
  newName: 235625001959.dkr.ecr.ap-northeast-2.amazonaws.com/ipiece-frontend
  newTag: 710360a8172e98287bc6075c48e919c4640f5c9c

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: ipiece-frontend
