apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: alb

    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    alb.ingress.kubernetes.io/group.name: ipiece
    alb.ingress.kubernetes.io/group.order: "10"   # ⭐ Grafana 규칙 먼저 적용

    alb.ingress.kubernetes.io/healthcheck-path: /grafana/api/health

    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:235625001959:certificate/ad38efac-da2d-494f-9bcb-8db272d92577
spec:
  ingressClassName: alb
  rules:
    - host: ipiece.store
      http:
        paths:
          - path: /grafana/
            pathType: Prefix
            backend:
              service:
                name: ipiece-monitoring-grafana
                port:
                  number: 80
