apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipiece-frontend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Woori-FISA-Go/ipiece-manifests.git'
    path: apps/frontend/overlays/prod
    targetRevision: develop
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ipiece-frontend-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
