apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipiece-backend-prod
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-or-health-change.slack-cicd: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/Woori-FISA-Go/ipiece-manifests
    targetRevision: develop
    path: apps/backend/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
