apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipiece-frontend-prod
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-or-health-change.slack-cicd: "true"
spec:
  project: default
  source:
    repoURL: 'https://github.com/Woori-FISA-Go/ipiece-manifests.git'
    path: apps/frontend/overlays/prod
    targetRevision: develop
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ipiece-frontend-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  # 🔥 프론트도 HPA가 replicas 조절하도록, Argo는 /spec/replicas는 무시
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: ipiece-frontend
      jsonPointers:
        - /spec/replicas
