apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipiece-external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Woori-FISA-Go/ipiece-manifests.git
    targetRevision: develop
    path: system/external-dns
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    # ExternalDNS는 보통 kube-system에 설치합니다 (권장)
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true